package com.xiaoheiwu.service.manager.configure;

public enum ServiceConfigureKey {
	STATUS,LIMIT,GRAY_PUBLISHI_ACCESS,GRAY_PUBLISHI_REFUSE,GRAY_PUBLISHI_REAR_ACCESS,GRAY_PUBLISHI_REAR_REFUSE
	,GRAY_PUBLISH_VERSION_MATCH,GRAY_PUBLISH_VERSION_RANGE;
}
